config_version: 4

release_procedures:
    release:
        name: release
        project: IP_Hyperscale
        procedure: sge-dynamic-procedure
        run_on_forks: False
        target:
            - master

    BlackDuck:
        project: IH_Olympium
        procedure: release_run_blackduck
        args:
            component: webrtc-signalig-server
            subcomponent: bundle
        target:
            - master

test_procedures:
    test:
        name: test
        project: IP_Hyperscale
        procedure: sge-dynamic-procedure
        target:
            - master

reviews:
    code_review:
        minimum_approvers: 1
        super_users:
            - cswci-gen
