version: '2.2'
services:
  webrtc-signaling-server:
    build: .
    expose: 
      - "9090"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webrtc-signaling-server
    ports:
      - "57779:57779"

