{
 "title": "Signaling Server",
 "description": "Signaling Server Statistics",
 "tags": [ "Signaling Server" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Connection Started",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "Connection connected to UI Successfully",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "Client Connections in queue",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "WebRtcUnallocatedConnections{connectionType=\"client\"}"
    }
   ]
  },
  {
   "title": "Application Connection in queue",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "Panel Title",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "WebRtcOpenConnections", "legendFormat": "{{status}} {{connectionType}}" }
   ]
  },
  {
   "title": "Signalig server Api latecy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_response_duration_seconds_sum{kubernetes_name=\"hyperscale-signaling\"}[100s]))  / sum(rate(http_response_duration_seconds_count{kubernetes_name=\"hyperscale-signaling\"}[100s])) ",
     "legendFormat": "{{ api }}"
    }
   ]
  }
 ]
}